In [1]:
import pandas as pd
import os

In [2]:
# Get the current working directory
pwd= os.getcwd()

In [3]:
# Manually specify the file paths
file_paths = [
    pwd + '/Zero1-NEW-OZOCK-SC - Brand1 - SC - Day - All Campaigns - May-01-2023 - May-29-2023.csv',
    'Zero1-NEW-OZOCK-SC  - search-t1 - SC - Day - All Campaigns - May-01-2023 - May-29-2023.csv',
    'Zero1-NEW-OZOCK-SC  -  search-t2 - SC - Day - All Campaigns - May-01-2023 - May-29-2023.csv',
    'Zero1-NEW-OZOCK-SC  -  search-t5 - SC - Day - All Campaigns - May-01-2023 - May-29-2023.csv',
    'Zero1-NEW-OZOCK-SC  -  search-t4 - SC - Day - All Campaigns - May-01-2023 - May-29-2023.csv',
    'Zero1-NEW-OZOCK-SC  -  search-t3 - SC - Day - All Campaigns - May-01-2023 - May-29-2023.csv',
    ]
    # Add more file paths as needed

In [4]:
# Create an empty list to store the dataframes
dataframes = []

In [5]:
# Loop through each file and read its contents into a dataframe
for file_path in file_paths:
    # Check if the file path exists
    if os.path.exists(file_path):
        # Read the file into a dataframe
        df = pd.read_csv(file_path)
        
        # Add a new column "reference" with the corresponding file name
        file_name = os.path.splitext(os.path.basename(file_path))[0]
        df['Reference'] = file_name
        
        # Append the dataframe to the list
        dataframes.append(df)

In [6]:
# Merge the dataframes into one dataframe
merged_data = pd.concat(dataframes, ignore_index=True)

In [7]:
#merged_data.to_excel("May1-May29.xlsx", index=False)

In [12]:
with pd.ExcelWriter("May1-May29.xlsx", engine='xlsxwriter') as writer:
    merged_data.to_excel(writer, index=False, sheet_name='Sheet1')
    worksheet = writer.sheets['Sheet1']
    
     # Specify the number format for numerical columns (e.g., '0.00' for two decimal places)
    numeric_format = writer.book.add_format({'num_format': '0.00'})
    for col_index, col in enumerate(merged_data.columns):
        if merged_data[col].dtype == 'float64' or merged_data[col].dtype == 'int64':
            worksheet.set_column(col_index, col_index, None, numeric_format)
            
    writer.save()

C:\Users\girish\AppData\Local\Temp\ipykernel_7568\1763635659.py:11: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()

### Set the output file path and name
output_file = 'path/to/output/merged.xlsx'

### Write the merged data to a new Excel file
merged_data.to_excel(output_file, index=False)

In [8]:
merged_data

,Date (US/Pacific),Spent,Viewable Impressions,Clicks,vCTR,Actual CPC,Conversion Rate,Conversions,Actual CPA,vCPM,Reference
0,"May 01, 2023",157.29,"3,255,376","2,416",0.07%,0.065,13.2%,319,0.493,0.05,Zero1-NEW-OZOCK-SC - Brand1 - SC - Day - All C...
1,"May 02, 2023",54.79,"1,114,568","1,237",0.11%,0.044,9.54%,118,0.464,0.05,Zero1-NEW-OZOCK-SC - Brand1 - SC - Day - All C...
2,"May 03, 2023",100.03,"1,277,217","1,675",0.13%,0.060,19.64%,329,0.304,0.08,Zero1-NEW-OZOCK-SC - Brand1 - SC - Day - All C...
3,"May 04, 2023",48.45,"533,090",963,0.18%,0.050,22.53%,217,0.223,0.09,Zero1-NEW-OZOCK-SC - Brand1 - SC - Day - All C...
4,"May 05, 2023",28.06,"82,719",234,0.28%,0.120,10.68%,25,1.122,0.34,Zero1-NEW-OZOCK-SC - Brand1 - SC - Day - All C...
...,...,...,...,...,...,...,...,...,...,...,...
167,"May 25, 2023",798.60,"3,752,885","41,354",1.1%,0.019,42.21%,"17,454",0.046,0.21,Zero1-NEW-OZOCK-SC - search-t3 - SC - Day - ...
168,"May 26, 2023",808.74,"2,755,443","37,673",1.37%,0.021,46.46%,"17,501",0.046,0.29,Zero1-NEW-OZOCK-SC - search-t3 - SC - Day - ...
169,"May 27, 2023",391.41,"1,114,050","17,961",1.61%,0.022,66.57%,"11,956",0.033,0.35,Zero1-NEW-OZOCK-SC - search-t3 - SC - Day - ...
170,"May 28, 2023",358.54,"667,685","17,858",2.67%,0.020,67.85%,"12,116",0.03,0.54,Zero1-NEW-OZOCK-SC - search-t3 - SC - Day - ...
171,"May 29, 2023",447.41,"1,266,721","23,995",1.89%,0.019,55.59%,"13,339",0.034,0.35,Zero1-NEW-OZOCK-SC - search-t3 - SC - Day - ...